name: Build Flatpak
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-flatpak:
    name: Build Flatpak Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get remove -y needrestart || true
          apt-get install -y git flatpak flatpak-builder python3 python3-pip wget sudo python3-aiohttp python3-tomlkit python3-yaml
          flatpak remote-add --system --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --system -y flathub org.freedesktop.Platform//25.08 org.freedesktop.Sdk//25.08
          flatpak install --system -y flathub org.freedesktop.Platform.codecs-extra//25.08-extra
          flatpak install --system -y flathub org.freedesktop.Sdk.Extension.rust-nightly//25.08
          flatpak install --system -y flathub org.freedesktop.Sdk.Extension.llvm21//25.08

      - name: Generate cargo sources
        working-directory: ./flatpak
        run: |
          python3 ./flatpak-builder-tools/cargo/flatpak-cargo-generator.py ../Cargo.lock -o cargo-sources.json

      - name: Build Flatpak
        working-directory: ./flatpak
        run: |
          flatpak-builder --repo=repo --force-clean build-dir gay.elysia.elysia.yml

      - name: Create bundle
        working-directory: ./flatpak
        run: |
          flatpak build-bundle repo elysia.flatpak gay.elysia.elysia
          sha512sum elysia.flatpak > elysia.flatpak.sha512sum

      - name: Upload artifact elysia.flatpak
        uses: actions/upload-artifact@v3
        with:
          name: elysia.flatpak
          path: ./flatpak/elysia.flatpak

      - name: Upload artifact elysia.flatpak.sha512sum
        uses: actions/upload-artifact@v3
        with:
          name: elysia.flatpak.sha512sum
          path: ./flatpak/elysia.flatpak.sha512sum
